# These are supported funding model platforms

github: [brew-o-doro]
open_collective: # Replace with a single Open Collective username
ko_fi: tedtke
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
custom: # Replace with a single custom sponsorship URL